display_name: Drift

icon: ..\..\assets\images\windows.ico

keywords:
  - Drift
  - Privacy
  - Proxy
  - V2ray
  - VLESS
  - WireGuard

generic_name: Drift

actions:
  - name: Start
    label: start
    arguments:
      - --start
  - name: Stop
    label: stop
    arguments:
      - --stop

categories:
  - Internet

startup_notify: true

include: []
