display_name: Drift
package_name: drift-vpn
maintainer:
  name: Drift
  email: support@drift-vpn.app

priority: optional
section: x11
installed_size: 6604
essential: false
icon: assets/images/source/ic_launcher_border.png

postinstall_scripts:
  - echo "Setting up Drift..."
  - sudo sed -i '/^\[Desktop Entry\]/a StartupWMClass=com.drift.vpn' "/usr/share/applications/drift.desktop"
  - for user_dir in /home/*; do if [ -f "$user_dir/.local/share/applications/drift.desktop" ]; then rm -f "$user_dir/.local/share/applications/drift.desktop"; fi; done
  - update-desktop-database /usr/share/applications
  - echo "Drift is ready to use :)"

postuninstall_scripts:
  - echo "Removing Drift user data..."
  - for user_dir in /home/*; do if [ -d "$user_dir/.local/share/drift" ]; then rm -rf "$user_dir/.local/share/drift"; fi; done
  - rm -rf /root/.local/share/drift
  - echo "Drift data cleanup complete."

keywords:
  - Drift
  - Privacy
  - Proxy
  - V2ray
  - VLESS
  - WireGuard

generic_name: Drift

categories:
  - Network

startup_notify: true
supported_mime_type:
  - x-scheme-handler/drift
  - x-scheme-handler/v2ray
  - x-scheme-handler/v2rayn
  - x-scheme-handler/v2rayng
  - x-scheme-handler/clash
  - x-scheme-handler/clashmeta
  - x-scheme-handler/sing-box

metainfo: linux/packaging/com.drift.vpn.appdata.xml
